openapi: 3.0.3

info:
  title: Tabellen
  version: 0.1.0

paths:
  /:
    get:
      operationId: tabellen.api.hello
      responses:
        200:
          description: Greeting
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /subscribe:
    post:
      operationId: tabellen.api.subscribe
      tags:
        - tomoru/subscribe
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tomoruCallbackUrl:
                  type: string
              required:
                - tomoruCallbackUrl
      callbacks:
        newMessage:
          "{$request.body#/tomoruCallbackUrl}":
            post:
              summary: Новое сообщение
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruEvent"
              responses:
                200:
                  description: Все ок
      responses:
        200:
          description: Подписка оформлена
