openapi: 3.0.3

info:
  title: Сообщения (Google Таблицы)
  version: 0.1.0
  description: |
    Микросервис для отправки сообщений клиентам из Google Таблицы.

    Чтобы воспользоваться микросервисом:
    1. Поделитесь доступом к таблице, хранящей список клиентов, с аккаунтом account@tomoru-tabellen.iam.gserviceaccount.com.
    2. Заполните поля конфигурации (идентификатор таблицы, столбец, начало/конец диапазона).
    3. Поставьте событие «Новое сообщение» в любом месте в логике диалога.
    4. Поставьте ноду с текстом отправляемого сообщения после события «Новое сообщение».
    5. Нажмите на кнопку «Отправить сообщение».
  x-config:
    schema:
      type: object
      properties:
        spreadsheetId:
          type: string
          description: Идентификатор Google Таблицы
        column:
          type: string
          description: Столбец
        rangeStart:
          type: integer
          description: Начало диапазона
        rangeEnd:
          type: integer
          description: Конец диапазона
      required:
        - spreadsheetId
        - column
        - rangeStart
        - rangeEnd

servers:
  - url: https://tomoru-tables.herokuapp.com

components:
  responses:
    UnknownError:
      description: Что-то пошло не так

paths:
  /send-message:
    post:
      operationId: tabellen.api.send_message
      summary: Отправить сообщение
      description: Отправить сообщение клиентам из Google Таблицы
      tags:
        - tomoru/action
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                botId:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/botId"
                config:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
              required:
                - botId
                - config
      responses:
        200:
          description: Сообщение отправлено
        424:
          description: Не найден вебхук для отправки сообщения
        500:
          $ref: "#/components/responses/UnknownError"

  /subscribe:
    post:
      operationId: tabellen.api.subscribe
      tags:
        - tomoru/subscribe
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tomoruCallbackUrl:
                  type: string
              required:
                - tomoruCallbackUrl
      callbacks:
        newMessage:
          "{$request.body#/tomoruCallbackUrl}":
            post:
              summary: Новое сообщение
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruEvent"
              responses:
                200:
                  description: Все ок
                500:
                  $ref: "#/components/responses/UnknownError"
      responses:
        200:
          description: Подписка оформлена
        500:
          $ref: "#/components/responses/UnknownError"
